version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 # Example runtime version; adjust as necessary
    commands:
      - echo "Installing dependencies"
      - npm install # or yarn install, if needed

  build:
    commands:
      - echo "Creating zip file for Lambda function"
      - zip -r Tokay_Automate.zip . # Package your code and dependencies into a zip file

artifacts:
  files:
    - Tokay_Automate.zip # Specify the name of your zip file
